<h5 dir=rtl>طراحی شده توسط سید امیرحسین حسینی جبلی: tel id=@amir_jebbeli</h5>

In [23]:
import pandas as pd

full_data = pd.read_csv('Airplane.csv')

full_data.head(5)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [24]:
# satisfaction = target
full_data['satisfaction'] = full_data['satisfaction'].map({"neutral or dissatisfied": 0, "satisfied": 1}).astype(float) 

# Gender
full_data['Gender'] = full_data['Gender'].fillna("unknown") 
full_data['Gender'] = full_data['Gender'].map({"Female": 0, "Male": 1}).astype(float)

# Customer Type
full_data['Customer Type'] = full_data['Customer Type'].fillna("unknown")
full_data['Customer Type'] = full_data['Customer Type'].map({"Loyal Customer": 0, "disloyal Customer": 1}).astype(float)

# Age
full_data['Age'] = full_data['Age'].fillna(full_data['Age'].median())
full_data.loc[full_data['Age'] <= 16 , 'Age']                            = 0 
full_data.loc[(full_data['Age'] > 16) & (full_data['Age'] <= 32), 'Age'] = 1
full_data.loc[(full_data['Age'] > 32) & (full_data['Age'] <= 48) , 'Age'] = 2
full_data.loc[(full_data['Age'] > 48) & (full_data['Age'] <= 64) , 'Age'] = 3
full_data.loc[(full_data['Age'] > 64) & (full_data['Age'] <= 85) , 'Age'] = 4

# Type of Travel
full_data['Type of Travel'] = full_data['Type of Travel'].fillna("unknown")
full_data['Type of Travel'] = full_data['Type of Travel'].map({"Personal Travel": 0, "Business travel": 1}).astype(float)

# Class
full_data['Class'] = full_data['Class'].fillna("unknown")
full_data['Class'] = full_data['Class'].map({"Business": 0, "Eco": 1, "Eco Plus" :2}).astype(float)

# Flight Distance
full_data['Flight Distance'] = full_data['Flight Distance'].fillna(full_data['Flight Distance'].median())
full_data.loc[full_data['Flight Distance'] <= 1000 , 'Flight Distance']                                          = 0 
full_data.loc[(full_data['Flight Distance'] > 1000) & (full_data['Flight Distance'] <= 2000), 'Flight Distance'] = 1
full_data.loc[(full_data['Flight Distance'] > 2000) & (full_data['Flight Distance'] <= 3000) , 'Flight Distance'] = 2
full_data.loc[(full_data['Flight Distance'] > 3000) & (full_data['Flight Distance'] <= 4000) , 'Flight Distance'] = 3
full_data.loc[(full_data['Flight Distance'] > 4000) & (full_data['Flight Distance'] <= 5000) , 'Flight Distance'] = 4

# Inflight wifi service
full_data['Inflight wifi service'] = full_data['Inflight wifi service'].fillna(full_data['Inflight wifi service'].median())

# Departure/Arrival time convenient
full_data['Departure/Arrival time convenient'] = full_data['Departure/Arrival time convenient'].fillna(full_data['Departure/Arrival time convenient'].median())

# Ease of Online booking
full_data['Ease of Online booking'] = full_data['Ease of Online booking'].fillna(full_data['Ease of Online booking'].median())

# Gate location
full_data['Gate location'] = full_data['Gate location'].fillna(full_data['Gate location'].median())

# Food and drink
full_data['Food and drink'] = full_data['Food and drink'].fillna(full_data['Food and drink'].median())

# Online boarding
full_data['Online boarding'] = full_data['Online boarding'].fillna(full_data['Online boarding'].median())

# Seat comfort
full_data['Seat comfort'] = full_data['Seat comfort'].fillna(full_data['Seat comfort'].median())

# Inflight entertainment
full_data['Inflight entertainment'] = full_data['Inflight entertainment'].fillna(full_data['Inflight entertainment'].median())

# On-board service
full_data['On-board service'] = full_data['On-board service'].fillna(full_data['On-board service'].median())

# Leg room service
full_data['Leg room service'] = full_data['Leg room service'].fillna(full_data['Leg room service'].median())

# Baggage handling
full_data['Baggage handling'] = full_data['Baggage handling'].fillna(full_data['Baggage handling'].median())

# Checkin service
full_data['Checkin service'] = full_data['Checkin service'].fillna(full_data['Checkin service'].median())

# Inflight service
full_data['Inflight service'] = full_data['Inflight service'].fillna(full_data['Inflight service'].median())

# Cleanliness
full_data['Cleanliness'] = full_data['Cleanliness'].fillna(full_data['Cleanliness'].median())

# Departure Delay in Minutes
full_data['Departure Delay in Minutes'] = full_data['Departure Delay in Minutes'].fillna(full_data['Departure Delay in Minutes'].median())
full_data.loc[full_data['Departure Delay in Minutes'] <= 300 , 'Departure Delay in Minutes']                                                     = 0 
full_data.loc[(full_data['Departure Delay in Minutes'] > 300) & (full_data['Departure Delay in Minutes'] <= 600), 'Departure Delay in Minutes'] = 1
full_data.loc[(full_data['Departure Delay in Minutes'] > 600) & (full_data['Departure Delay in Minutes'] <= 900), 'Departure Delay in Minutes'] = 2
full_data.loc[(full_data['Departure Delay in Minutes'] > 900) & (full_data['Departure Delay in Minutes'] <= 1200), 'Departure Delay in Minutes'] = 3
full_data.loc[(full_data['Departure Delay in Minutes'] > 1200) & (full_data['Departure Delay in Minutes'] <= 1592), 'Departure Delay in Minutes'] = 4

# Arrival Delay in Minutes
full_data['Arrival Delay in Minutes'] = full_data['Arrival Delay in Minutes'].fillna(full_data['Arrival Delay in Minutes'].median())
full_data.loc[full_data['Arrival Delay in Minutes'] <= 300 , 'Arrival Delay in Minutes']                                                     = 0 
full_data.loc[(full_data['Arrival Delay in Minutes'] > 300) & (full_data['Arrival Delay in Minutes'] <= 600), 'Arrival Delay in Minutes'] = 1
full_data.loc[(full_data['Arrival Delay in Minutes'] > 600) & (full_data['Arrival Delay in Minutes'] <= 900), 'Arrival Delay in Minutes'] = 2
full_data.loc[(full_data['Arrival Delay in Minutes'] > 900) & (full_data['Arrival Delay in Minutes'] <= 1200), 'Arrival Delay in Minutes'] = 3
full_data.loc[(full_data['Arrival Delay in Minutes'] > 1200) & (full_data['Arrival Delay in Minutes'] <= 1584), 'Arrival Delay in Minutes'] = 4

# train test split

In [25]:
from sklearn.model_selection import train_test_split


X = full_data.drop(columns=['Unnamed: 0', 'id', 'satisfaction'])  # Features
y = full_data['satisfaction']  # Target

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print sizes
print(len(X_train), len(X_test))

83123 20781

In [26]:
print(full_data[['Gender','satisfaction']].groupby(['Gender'], as_index=False).mean())

print(full_data[['Customer Type','satisfaction']].groupby(['Customer Type'], as_index=False).mean())

print(full_data[['Age','satisfaction']].groupby(['Age'], as_index=False).mean())

print(full_data[['Type of Travel','satisfaction']].groupby(['Type of Travel'], as_index=False).mean())

print(full_data[['Class','satisfaction']].groupby(['Class'], as_index=False).mean())

print(full_data[['Flight Distance','satisfaction']].groupby(['Flight Distance'], as_index=False).mean())

print(full_data[['Inflight wifi service','satisfaction']].groupby(['Inflight wifi service'], as_index=False).mean())

print(full_data[['Departure/Arrival time convenient','satisfaction']].groupby(['Departure/Arrival time convenient'], as_index=False).mean())

print(full_data[['Ease of Online booking','satisfaction']].groupby(['Ease of Online booking'], as_index=False).mean())

print(full_data[['Gate location','satisfaction']].groupby(['Gate location'], as_index=False).mean())

print(full_data[['Food and drink','satisfaction']].groupby(['Food and drink'], as_index=False).mean())

print(full_data[['Online boarding','satisfaction']].groupby(['Online boarding'], as_index=False).mean())

print(full_data[['Seat comfort','satisfaction']].groupby(['Seat comfort'], as_index=False).mean())

print(full_data[['Inflight entertainment','satisfaction']].groupby(['Inflight entertainment'], as_index=False).mean())

print(full_data[['On-board service','satisfaction']].groupby(['On-board service'], as_index=False).mean())

print(full_data[['Leg room service','satisfaction']].groupby(['Leg room service'], as_index=False).mean())

print(full_data[['Baggage handling','satisfaction']].groupby(['Baggage handling'], as_index=False).mean())

print(full_data[['Checkin service','satisfaction']].groupby(['Checkin service'], as_index=False).mean())

print(full_data[['Inflight service','satisfaction']].groupby(['Inflight service'], as_index=False).mean())

print(full_data[['Cleanliness','satisfaction']].groupby(['Cleanliness'], as_index=False).mean())

print(full_data[['Departure Delay in Minutes','satisfaction']].groupby(['Departure Delay in Minutes'], as_index=False).mean())

print(full_data[['Arrival Delay in Minutes','satisfaction']].groupby(['Arrival Delay in Minutes'], as_index=False).mean())

   Gender  satisfaction
0     0.0      0.427371
1     1.0      0.439475
   Customer Type  satisfaction
0            0.0      0.477291
1            1.0      0.236658
   Age  satisfaction
0    0      0.152440
1    1      0.353365
2    2      0.511321
3    3      0.531141
4    4      0.184288
   Type of Travel  satisfaction
0             0.0      0.101678
1             1.0      0.582597
   Class  satisfaction
0    0.0      0.694251
1    1.0      0.186138
2    2.0      0.246064
   Flight Distance  satisfaction
0                0      0.329510
1                1      0.460537
2                2      0.647019
3                3      0.775679
4                4      0.551724
   Inflight wifi service  satisfaction
0                      0      0.997422
1                      1      0.325448
2                      2      0.248664
3                      3      0.250580
4                      4      0.598969
5                      5      0.990758
   Departure/Arrival time convenient  satisfaction
0                                  0      0.475472
1                                  1      0.486579
2                                  2      0.445407
3                                  3      0.438217
4                                  4      0.387771
5                                  5      0.425300
   Ease of Online booking  satisfaction
0                       0      0.664141
1                       1      0.376034
2                       2      0.303942
3                       3      0.308274
4                       4      0.530939
5                       5      0.738286
   Gate location  satisfaction
0              0      1.000000
1              1      0.495559
2              2      0.460712
3              3      0.347202
4              4      0.388520
5              5      0.572376
   Food and drink  satisfaction
0               0      0.467290
1               1      0.200047
2               2      0.387939
3               3      0.396368
4               4      0.524981
5               5      0.549007
   Online boarding  satisfaction
0                0      0.556425
1                1      0.137767
2                2      0.115338
3                3      0.135709
4                4      0.623041
5                5      0.871771
   Seat comfort  satisfaction
0             0      0.000000
1             1      0.223188
2             2      0.224139
3             3      0.211543
4             4      0.561152
5             5      0.650208
   Inflight entertainment  satisfaction
0                       0      0.000000
1                       1      0.139846
2                       2      0.213302
3                       3      0.270077
4                       4      0.611766
5                       5      0.648435
   On-board service  satisfaction
0                 0      0.000000
1                 1      0.193733
2                 2      0.255705
3                 3      0.315683
4                 4      0.536852
5                 5      0.642422
   Leg room service  satisfaction
0                 0      0.351695
1                 1      0.202840
2                 2      0.274673
3                 3      0.272415
4                 4      0.582306
5                 5      0.614465
   Baggage handling  satisfaction
0                 1      0.297637
1                 2      0.295460
2                 3      0.235847
3                 4      0.480914
4                 5      0.612694
   Checkin service  satisfaction
0                0      0.000000
1                1      0.239255
2                2      0.252307
3                3      0.448288
4                4      0.459921
5                5      0.609777
   Inflight service  satisfaction
0                 0      0.000000
1                 1      0.289949
2                 2      0.301213
3                 3      0.238977
4                 4      0.477770
5                 5      0.609972
   Cleanliness  satisfaction
0            0      0.000000
1            1      0.196201
2            2      0.212993
3            3      0.431879
4            4      0.535340
5            5      0.608797
   Departure Delay in Minutes  satisfaction
0                           0      0.433449
1                           1      0.388646
2                           2      0.272727
3                           3      0.400000
4                           4      0.500000
   Arrival Delay in Minutes  satisfaction
0                       0.0      0.433453
1                       1.0      0.392405
2                       2.0      0.181818
3                       3.0      0.400000
4                       4.0      0.500000

In [27]:
X_train.head(5)

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
20921,0.0,0.0,3,0.0,1.0,1,4,5,4,1,...,5,2,2,4,3,5,2,4,0,0.0
36897,0.0,1.0,2,1.0,0.0,0,4,4,4,2,...,5,1,4,2,4,3,5,1,0,0.0
8468,1.0,0.0,4,0.0,1.0,0,2,3,2,1,...,1,1,5,4,5,5,5,1,0,0.0
53490,0.0,0.0,4,0.0,1.0,2,3,5,3,4,...,4,5,5,3,5,3,5,5,0,0.0
78687,0.0,1.0,1,1.0,1.0,1,2,2,2,3,...,1,1,1,2,3,5,2,1,0,0.0

In [28]:
X_test.head(5)

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
80638,0.0,0.0,1,0.0,1.0,0,2,4,2,5,...,5,5,5,4,4,3,5,5,0,0.0
43398,1.0,0.0,1,1.0,0.0,0,3,5,5,5,...,3,3,1,1,3,2,3,3,0,0.0
32751,0.0,0.0,3,0.0,1.0,0,1,3,1,3,...,3,4,4,1,4,3,4,4,0,0.0
33571,0.0,0.0,1,0.0,1.0,1,2,3,2,4,...,4,4,3,2,4,1,4,4,0,0.0
71287,1.0,1.0,2,1.0,0.0,1,2,2,2,1,...,5,2,2,2,3,2,2,2,0,0.0

In [29]:
y_train

20921     0.0
36897     0.0
8468      0.0
53490     0.0
78687     0.0
         ...
54886     0.0
76820     0.0
103694    0.0
860       1.0
15795     0.0
Name: satisfaction, Length: 83123, dtype: float64

In [30]:
y_test

80638    0.0
43398    0.0
32751    0.0
33571    0.0
71287    0.0
        ...
8158     0.0
53718    0.0
33319    0.0
99162    1.0
96811    1.0
Name: satisfaction, Length: 20781, dtype: float64

# Node Class

In [31]:
class Node():
    def __init__(self, feature_index=None, thresholds=None, children=None, info_gain=None, value=None):
        self.feature_index = #TODO
        self.thresholds = #TODO
        self.children = #TODO
        self.info_gain = #TODO
        self.value = #TODO



class DecisionTreeClassifier():
    def __init__(self, min_sample_split=2, max_depth=2, num_splits=3):
        self.root = None
        self.min_sample_split = min_sample_split
        self.max_depth = max_depth
        self.num_splits = num_splits  

    def build_tree(self, dataset, curr_depth=0):
        X, Y = dataset[:, :-1], dataset[:, -1]
        num_samples, num_features = np.shape(X)

        if num_samples >= self.min_sample_split and curr_depth <= self.max_depth:
            best_split = self.get_best_split(dataset, num_samples, num_features)
            if best_split["info_gain"] > 0:
                children = [self.build_tree(subset, curr_depth + 1) for subset in best_split["datasets"]]
                return Node(feature_index=best_split["feature_index"], thresholds=best_split["thresholds"], 
                            children=children, info_gain=best_split["info_gain"])

        leaf_value = self.calculate_leaf_value(Y)
        return Node(value=leaf_value)


    def get_best_split(self, dataset, num_samples, num_features):
        best_split = {"info_gain": -float("inf")}
        
        for feature_index in range(num_features):
            #TODO

        return best_split

    def split(self, dataset, feature_index, thresholds):
        subsets = []
        #TODO

    def information_gain(self, parent, children, mode="entropy"):
        #TODO

        return gain

    def entropy(self, y):
        #TODO
        return entropy

    def gini_index(self, y):
        #TODO
        return gini

    def calculate_leaf_value(self, Y):
        return max(set(Y), key=list(Y).count)

    def print_tree(self, tree=None, indent=""):
        #TODO

    def fit(self, X, Y):
        #TODO

    def predict(self, X):
        #TODO

    def make_prediction(self, x, tree):
        if tree.value is not None:
            return tree.value

        feature_val = x[tree.feature_index]

        for i, threshold in enumerate(tree.thresholds):
            if feature_val <= threshold:
                return self.make_prediction(x, tree.children[i])

        return self.make_prediction(x, tree.children[-1])

SyntaxError: invalid syntax (1658516493.py, line 3)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.metrics import accuracy_score

classifier = DecisionTreeClassifier(min_samples_split=10, max_depth=17)
classifier.fit(X_train, Y_train)
train_predictions  = classifier.predict(X_train)
test_predictions = classifier.predict(X_test)

train_accuracy = accuracy_score(Y_train, train_predictions)
test_accuracy = accuracy_score(Y_test, test_predictions)
print('Test Accuracy:', test_accuracy) 
print('Train Accuracy:', train_accuracy)